# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(566, 581)
        MainWindow.setStyleSheet("backround-color: seagreen")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Generation_password_2 = QtWidgets.QLabel(self.centralwidget)
        self.Generation_password_2.setGeometry(QtCore.QRect(160, 50, 247, 40))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(22)
        self.Generation_password_2.setFont(font)
        self.Generation_password_2.setObjectName("Generation_password_2")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(150, 150, 256, 35))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.result.setFont(font)
        self.result.setObjectName("result")
        self.Use_Cifri = QtWidgets.QCheckBox(self.centralwidget)
        self.Use_Cifri.setGeometry(QtCore.QRect(40, 250, 314, 37))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Use_Cifri.setFont(font)
        self.Use_Cifri.setObjectName("Use_Cifri")
        self.use_bukvi = QtWidgets.QCheckBox(self.centralwidget)
        self.use_bukvi.setGeometry(QtCore.QRect(40, 290, 307, 33))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.use_bukvi.setFont(font)
        self.use_bukvi.setObjectName("use_bukvi")
        self.Generation_password = QtWidgets.QPushButton(self.centralwidget)
        self.Generation_password.setGeometry(QtCore.QRect(170, 380, 222, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Generation_password.setFont(font)
        self.Generation_password.setStyleSheet("background-color: seagreen;\n"
"color: white;\n"
"border: 2px solid black;\n"
"border-radius: 10px;")
        self.Generation_password.setObjectName("Generation_password")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 566, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Generation_password_2.setText(_translate("MainWindow", "Генератор паролів"))
        self.result.setText(_translate("MainWindow", "Тут буде результат"))
        self.Use_Cifri.setText(_translate("MainWindow", "Використовувати числа"))
        self.use_bukvi.setText(_translate("MainWindow", "Використовувати алфавіт"))
        self.Generation_password.setText(_translate("MainWindow", "Генерувати пароль"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
